### ISSUE TITLE
Mod required on clients

### ISSUE THREAD

**Issue by Beanstalkdoodle** [FoalFreePress/ServerRestarter#1]
Hello 
I have installed the server restarter both on my server with 1.12.2 Infinity evolved reloaded and after receiving the following error message also on my client:

XXXXXXX lost connection: Server Mod rejections:
Server Restart: Requires version 1 but mod is not found on client.

After installing it on client i still cannot join the server for some reason.
Am I doing something wrong or is the 1.12.2 version of the server restarter bugged on client side?
Also when i look into the mod list on the running client i cannot find the ServerRestarter-1.12.2-44967da.jar in the mod list, so it seems like the mod does not load on client. 
Can you help?

**Comment by ShroomAgent27** [comment]
Interesting, I'll take a look at this when I'm next available.

**Comment by ShroomAgent27** [comment]
Jar uploaded to CurseForge. It'll be available to download when it gets approved.

**Comment by Beanstalkdoodle** [comment]
> Jar uploaded to CurseForge. It'll be available to download when it gets approved.

Thank you very much! does it now require to be installed on client side or is server side enough?
Just deleting the old jar file from the servers modlist and replacing it or does restarting the server automatically pull the new jar?

**Comment by ShroomAgent27** [comment]
Now it's true server side only. Delete the old version. It won't automatically upsate.

**Comment by Adashzon** [comment]
> Now it's true server side only. Delete the old version. It won't automatically upsate.

I'm still getting the issue 
"Server Restart: Requires version 1 but mod is not found on client."

I downloaded the latest version for 1.12.2 on cursed forge

**Comment by ShroomAgent27** [comment]
I cannot reproduce this.

Using version 1.12.2-d963e7e I am able to join with the mod loaded on even a vanilla client.
